

```{r setup, include=FALSE}
library(tidyr)
library(data.table)
library(ggfortify)
library(broom) #tidy() augment()
library(dplyr)
library(ggplot2)
library(cowplot)
library(lme4)
library(lmerTest)
library(scales)
library(reshape2)
library(stats) 
library(zoo)
library(sciplot)
library(jagsUI)
library(chron)
 
#setwd("~/Documents/SAFS/PigeonGuillemots")
path <- getActiveDocumentContext()$path 
setwd(dirname(path))

# knitr::opts_chunk$set(echo = TRUE)
```


```{r set up}

#load data from PigeonGuillemot_whidbey.Rmd
#contains single row where burrow_name == NA when no activity was detected, but survey started
data_burrow_all <- read.csv("data_burrow.csv", header = T, stringsAsFactors = F) %>%
  filter(region == 'Whidbey') %>%
  dplyr::select(-c(Gunnel, Sculpin, Other)) %>%
  #filter(site %in% c('Mutiny Sands', 'Double Bluff North')) %>%
  #filter(year > 2016) %>%
  distinct()  #2 duplicates, all lagoon south 2017

#study start day per year, island-wide
start_end_all <- data_burrow_all %>%
  group_by(year, region) %>%
  summarize(start_day = min(yday, na.rm = T), end_day = max(yday, na.rm = T))

no_vis <- data_burrow_all %>%
  filter(is.na(burrow_name)) %>%
  dplyr::select(region, year, site, week, yday)

all_days <- data_burrow_all %>%
  #filter(is.na(burrow_name)) %>%
  group_by(region, year, site) %>%
  distinct(yday)
fill <- data_burrow_all %>%  #all day-burrow combinations
  filter(!is.na(burrow_name)) %>%
  group_by(region, year, site, burrow_name) %>%
  distinct(burrow_name) %>%
  merge(all_days, all = T) 

burrow <- data_burrow_all %>%
  filter(!is.na(burrow_name)) %>% #remove all dummy rows where no burrows were seen
  merge(fill, by = c('region', 'site', 'year', 'burrow_name', 'yday'), all = T) %>%
  merge(start_end_all, by = c('region', 'year'), all = T) %>%
  transform(study_day = yday - start_day + 1) #%>% arrange(burrow_name)

#burrow visit and prey visit start stops
prey_start_end <- burrow %>%
  filter(tot_prey > 0) %>%
  group_by(region, year, site, burrow_name) %>%
  summarize(prey_start = min(study_day), prey_end = max(study_day))  

bv_start_end <- burrow %>%
  filter(burrow_visit > 0) %>%
  group_by(region, year, site, burrow_name) %>%
  summarize(bv_start = min(study_day), bv_end = max(study_day))  

start_end_visits <- prey_start_end %>%
  merge(bv_start_end, by = c('region', 'year', 'site', 'burrow_name'), all = T)

day_range <- burrow %>%
  group_by(region, year, site) %>%
  summarize(min_day = min(study_day, na.rm = T), max_day = max(study_day, na.rm = T))

week_range <- burrow %>%
  group_by(region, year, site) %>%
  summarize(min_week = min(week), max_week = max(week))

n_visits <- burrow %>%
  group_by(region, year, site) %>% #don't include burrow here, since hasn't been expanded yet
  summarize(n_visits = n_distinct(study_day)) #use study_day instead of date - NAs in date

#combining all data with dummy framework of all days, create capture history
burrow_CH <- burrow %>%
  merge(start_end_visits, by = c('region', 'year', 'site', 'burrow_name'), all.x = T) %>%
  transform(prey_days = prey_end + 1 - prey_start) %>%
  transform(bv_days = bv_end + 1 - bv_start) %>%
  group_by(region, year, site) %>%
  merge(day_range, by = c('region', 'year', 'site')) %>%
  merge(n_visits, by = c('region', 'year', 'site')) %>% #arrange(burrow_name)
  transform(capt_hist = ifelse(is.na(burrow_visit) & is.na(tot_prey), 3, #observed but not detected
                     ifelse(burrow_visit == 0 & tot_prey == 0, 3, #observed but not detected
              ifelse(tot_prey > 0, 2, #prey visit
              ifelse(burrow_visit > 0, 1, #burrow visit
                       100))))) %>% 
  select(region, year, site, week, yday, start_day, study_day, n_visits, 
         min_day, max_day, burrow_name, capt_hist) %>% distinct() %>%
  dcast(region + year + site + burrow_name + min_day + max_day ~ study_day, value.var = 'capt_hist', 
        fun.aggregate = mean) %>%
  filter(!is.na(burrow_name)) %>%
  melt(id.vars = c('region', 'year', 'site', 'burrow_name', 'min_day', 'max_day')) %>%
  transform(study_day = as.numeric(as.character(variable))) %>% 
  transform(capt_hist = ifelse(study_day < min_day | study_day > max_day, NA, value)) %>%
  dplyr::select(region, year, site, burrow_name, study_day, capt_hist) %>% #NA outside start/stop days
  dcast(region + year + site + burrow_name ~ study_day, value.var = 'capt_hist') 

#df of survey days at burrow-week level
survey <- burrow %>%
  merge(n_visits, by = c('region', 'year', 'site')) %>%
  merge(week_range, by = c('region', 'year', 'site')) %>%
  #transform(occ = week-min_week) %>%
  dplyr::select(region, year, site, yday, burrow_name, study_day, n_visits, week, max_week) %>%
  #dcast(region + year + site + burrow_name + n_visits ~ week, value.var = 'study_day', fun.aggregate = mean)
  dcast(region + year + site + n_visits + burrow_name ~ study_day, value.var = 'study_day', fun.aggregate = mean)

max_recap <- max(survey$n_visits) #max number of resights for ncol, NOT distinct study days

```

```{r}

####augment - need to add X individuals prop to # of nests with the same days at a site but all obs == 3

#number of nests per site per year - for proportion
num_nests <- burrow %>%
  group_by(region, year, site) %>%
  summarize(nest_cnt = n_distinct(burrow_name)) %>%
  transform(burrow_name = 'XXX') %>%
  merge(n_visits, by = c('region', 'year', 'site')) %>%
  transform(aug = round(0.2*nest_cnt)) %>%
  transform(aug = ifelse(aug < 1, 1, aug)) %>%
  dplyr::select(-nest_cnt)

aug_fun <- function(df, id_cols, visit_col){
  # Keep only the needed columns. 
  cols <- append(id_cols, visit_col)
  df_down_select <- df %>% select(cols)
  # Create a storage data frame
  final_df <- data.frame(stringsAsFactors = FALSE)
  # Loop through the data frame
  for (i in 1:nrow(df_down_select)){
    # Replicate the id data based on the number of visits
    list_rep <- rep(df_down_select[i, id_cols], df_down_select[i, visit_col])
    # Convert the resulting list to a data frame
    current_df <- as.data.frame(matrix(unlist(list_rep),
                                       nrow = df_down_select[i, visit_col],
                                       byrow = TRUE),
                                stringsAsFactors = FALSE)
    final_df <- bind_rows(final_df, current_df)
  }
  return(final_df)
}

aug_id <- aug_fun(num_nests, c('region', 'year', 'site', 'burrow_name', 'n_visits'), 'aug') %>%
  transform(V4 = 'XXX')
colnames(aug_id) <- c('region', 'year', 'site', 'burrow_name', 'n_visits') 

#take just id cols and days
days_obs <- survey %>%
  dplyr::select(-c(burrow_name)) %>%
  distinct()

#merge id columns and day observation columns
aug_inds <- aug_id %>%
  merge(days_obs, by = c('region', 'year', 'site', 'n_visits'), all = T) %>%
  transform(year = as.numeric(year))
colnames(aug_inds) <- colnames(survey)

#take augmented survey day data and turn to '3' obs
ch_obs <- days_obs
for (i in 1:nrow(ch_obs)) {
  for (j in 5:ncol(ch_obs)) {
    if (!is.nan(ch_obs[i,j])) {
      ch_obs[i,j] <- 3
    }
  }
}

aug_inds_CH <- aug_id %>%
  merge(ch_obs, by = c('region', 'year', 'site', 'n_visits'), all = T) %>%
  transform(year = as.integer(year)) %>%
  dplyr::select(-n_visits)
colnames(aug_inds_CH) <- colnames(burrow_CH)

burrow_CH_aug <- burrow_CH %>%
  bind_rows(aug_inds_CH) 

##collapse so that all data are at beginning, trailing NAs for the rest
ch_dat <- matrix(NA, nrow = dim(burrow_CH_aug)[1], ncol = max_recap)

for (i in 1:dim(burrow_CH_aug)[1]) {
  temp <- as.numeric(burrow_CH_aug[i, 4 + c(which(!is.na(burrow_CH_aug[i,5:dim(burrow_CH_aug)[2]])))])
  num <- length(temp)
  ch_dat[i,] <- c(temp, rep(NA, max_recap-num))
}

max_visits <- max(n_visits$n_visits)

surv_aug <- survey %>%
  bind_rows(aug_inds %>% transform(n_visits = as.numeric(n_visits)))

survey <- surv_aug

survey_days <- matrix(NA, nrow = dim(survey)[1], ncol = max_visits)

for (i in 1:dim(survey)[1]) {
  temp <- as.numeric(survey[i, 5 + c(which(!is.na(survey[i,6:dim(survey)[2]])))])
  num <- length(temp)
  survey_days[i,] <- c(temp, rep(NA, max_visits-num))
}

year_i <- as.numeric(factor(burrow_CH_aug$year))
site_i <- survey$site
visits_i <- survey$n_visits

```

```{r}

# write.csv(survey_days, 'survey_days.csv', row.names = F)
# write.csv(ch_dat, 'ch_dat.csv', row.names = F)

```


```{r covariates}

#sst
sst <- read.csv('sst_day.csv', header = T, stringsAsFactors = F) %>%
  #transform(year = factor(year)) %>%
  filter(station == 9444900) %>% #CHECK if this is the north seattle station!
  dplyr::select(-c(station, month, day)) %>%
  merge(burrow %>% dplyr::select(yday, year, study_day) %>% distinct(), by = c('year', 'yday')) 

#tides
tides <- read.csv("tides_all.csv", stringsAsFactors = F, header = T) %>%
  transform(date = as.Date(date)) %>%
  transform(month = month(date)) %>%
  transform(time = as.POSIXct(time)) 
    
#high and low tides, dim from data_count doubles
## problematic to use the count data since some dates are missing compared to burrow (maylor 2008)
PG_covs <- burrow %>% 
  filter(region == 'Whidbey') %>%
  #filter(PG_count != '') %>% 
  dplyr::select(region, year, site, date, start_time, week, yday, burrow_name, burrow_visit, tot_prey,
         start_day, end_day, study_day) %>%
  transform(date = as.Date(date)) %>%
  merge(tides %>% filter(region == 'Whidbey'), by = c('site', 'date', 'region'), all.x = T) %>%
  transform(start_time = ifelse(start_time == "0:00" | start_time == "" | is.na(start_time), 
                                "8:00", start_time)) %>%
  transform(survey = as.POSIXlt(paste0(paste(date, start_time, sep = " "), ":00"), 
                                format = "%Y-%m-%d %H:%M:%OS")) %>%
  transform(from_low = ifelse(type == "L", as.numeric(time-survey, units = "mins"), NA),
            from_high = ifelse(type == "H", as.numeric(time-survey, units = "mins"), NA)) %>%
  transform(from_hilo = as.numeric(coalesce(from_low, from_high))) %>%
  select(-c(t, month, from_low, from_high)) %>%
  transform(time_stamp = times(format(time, format = "%H:%M:%S"))) %>%
  transform(rank = ifelse(time_stamp <= "2:30:00" | time_stamp >= "21:00:00", 1,
                          ifelse(time_stamp > "3:00:00" & time_stamp <= "9:00:00", 2,
                                 ifelse(time_stamp > "17:00:00", 4, 3)))) %>%
  filter(rank == 2 | rank == 3) %>%
  filter(type == 'H') %>%
  dplyr::select(region, year, site, date, v, from_hilo,
                burrow_name, burrow_visit, tot_prey, start_day, end_day, study_day) %>%
  merge(sst, by = c('study_day', 'year'), all.x = T) %>%
  dplyr::select(region, year, site, yday, study_day, burrow_name, burrow_visit, tot_prey, from_hilo, v, temp)

write.csv(PG_covs, 'PG_covs.csv', row.names = F)

```


```{r ch} 

# all_dat <- burrow_CH %>%
#   merge(PG_covs, by = c('region', 'year', 'site', 'study_day', 'burrow_name'), all = T)

# write.csv(days_since, "days_since.csv", row.names = F) 
# write.csv(burrow_CH, "burrow_CH.csv", row.names = F) 
# write.csv(all_dat, 'all_dat.csv', row.names = F)
  
```


