---
title: ""
output: word_document
---

```{r setup, include=FALSE}
library(tidyr)
library(data.table)
library(ggfortify)
library(broom) #tidy() augment()
library(dplyr)
library(ggplot2)
library(cowplot)
library(lme4)
library(lmerTest)
library(scales)
library(reshape2)
library(stats) 
library(zoo)
library(sciplot)
library(jagsUI)
 
setwd("~/Documents/R/SAFS/PigeonGuillemots")
path <- getActiveDocumentContext()$path 
setwd(dirname(path))

# knitr::opts_chunk$set(echo = TRUE)
```


```{r set up long df}

#load data from PigeonGuillemot_whidbey.Rmd
#contains single row where burrow_name == NA when no activity was detected, but survey starte
data_burrow_all <- read.csv("data_burrow.csv", header = T, stringsAsFactors = F) %>%
  filter(region == 'Whidbey') %>%
  dplyr::select(-intern_data) %>%
  dplyr::select(-c(Gunnel, Sculpin, Other)) %>%
  distinct()  #7 duplicates, all lagoon south 2017

data_count <- read.csv("data_count.csv", header = T, stringsAsFactors = F) %>%
  select(-intern_data)

#study start day per year, island-wide
start_end_all <- data_burrow_all %>%
  group_by(year, region) %>%
  summarize(start_day = min(yday), end_day = max(yday))

burrow <- data_burrow_all %>%
  #distinct() %>%
  merge(start_end_all, by = c('region', 'year'), all = T) %>%
  transform(study_day = yday - start_day + 1)  

#dup_test <- burrow[duplicated(burrow),]

#burrow visit and prey visit start stops
prey_start_end <- burrow %>%
  filter(tot_prey > 0) %>%
  group_by(region, year, site, burrow_name) %>%
  summarize(prey_start = min(study_day), prey_end = max(study_day))  

bv_start_end <- burrow %>%
  filter(burrow_visit > 0) %>%
  group_by(region, year, site, burrow_name) %>%
  summarize(bv_start = min(study_day), bv_end = max(study_day))  

start_end_visits <- prey_start_end %>%
  merge(bv_start_end, by = c('region', 'year', 'site', 'burrow_name'), all = T)
# no_start <- start_end_visits %>%  #45% 8/1/18
#   filter(prey_start > bv_start | is.na(bv_start)) %>% nrow()/nrow(start_end_visits)
# no_end <- start_end_visits %>% #6% 8/1/18
#   filter(prey_end == bv_start) %>% nrow()/nrow(start_end_visits)

#df of all days to merge into actual observations below
all_days <- data.frame(c(0, seq(1:81))) #create dummy first day
names(all_days) <- 'study_day'

```

```{r covariates}

#sst
sst <- read.csv('sst_day.csv', header = T, stringsAsFactors = F) %>%
  #transform(year = factor(year)) %>%
  filter(station == 9444900) %>% #CHECK if this is the north seattle station!
  dplyr::select(-c(station, month, day)) %>%
  merge(burrow %>% dplyr::select(yday, year, study_day) %>% distinct(), by = c('year', 'yday'))

#tides
tides <- read.csv("tides_all.csv", stringsAsFactors = F, header = T) %>%
  transform(date = as.Date(date)) %>%
  transform(month = month(date)) %>%
  transform(time = as.POSIXct(time))
    
#high and low tides, dim from data_count doubles
PG_count_tides <- data_count %>% 
  filter(PG_count != '') %>% 
  select(region, site, date, PG_count, start_time) %>%
  transform(date = as.Date(date)) %>%
  inner_join(tides, by = c('site', 'date', 'region')) %>%
  transform(start_time = ifelse(start_time == "0:00" | start_time == "", "8:00", start_time)) %>%
  transform(survey = as.POSIXlt(paste0(paste(date, start_time, sep = " "), ":00"))) %>%
  transform(from_low = ifelse(type == "L", as.numeric(time-survey, units = "mins"), NA),
            from_high = ifelse(type == "H", as.numeric(time-survey, units = "mins"), NA)) %>%
  transform(from_hilo = as.numeric(coalesce(from_low, from_high))) %>%
  select(-c(t, month, from_low, from_high)) %>%
  transform(time_stamp = times(format(time, format = "%H:%M:%S"))) %>%
  transform(rank = ifelse(time_stamp <= "2:30:00" | time_stamp >= "21:00:00", 1,
                          ifelse(time_stamp > "3:00:00" & time_stamp <= "9:00:00", 2,
                                 ifelse(time_stamp > "17:00:00", 4, 3)))) %>%
  filter(rank == 2 | rank == 3) %>%
  filter(region == 'Whidbey')

table(PG_count_tides$rank)

# test <- PG_count_tides %>%
#   group_by(site, date) %>%
#   summarize(cnt = n_distinct(v)) %>%
#   filter(cnt < 2)

# #data for covariate on counts - trimmmed to July/Aug to see effect at max bird occupancy
# PG_count_tides_trim <- PG_count_tides %>%
#   transform(month = month(date)) %>%
#   #filter(month > 6 & month < 9) %>%
#   filter(region == 'Whidbey')

#data for covariate on prey deliveries/CH
tides_dat <- PG_count_tides %>%
  filter(region == 'Whidbey') %>%
  filter(type == 'H') %>%
  dplyr::select(region, site, date, v, type, from_hilo) 
#need to grab study_day and merge onto tides df
dates <- burrow %>%
  filter(region == 'Whidbey') %>%
  dplyr::select(year, date, yday, study_day, burrow_name) %>% distinct() %>%
  transform(date = as.Date(date))

covs_dat <- tides_dat %>%
  merge(dates, by = c('date'), all = F) %>%
  merge(sst, by = c('study_day', 'yday', 'year'), all = T)

```


```{r ch} 
# Create capture history

#df containing all unique site-burrow_name-study days where visits occured to create NAs for undetected burrows specifically when other burrows WERE seen

burrow_00 <- burrow %>%  #list of non-visit days
  filter(!is.na(burrow_name)) %>%
  distinct(region, site, year, study_day)
burrow_0 <- burrow %>% #list of visit days and non-visit days
  filter(is.na(burrow_name)) %>%
  distinct(region, site, year, study_day) %>%
  bind_rows(burrow_00)

#all days
burrow_name_expand <- burrow %>%
  filter(!is.na(burrow_name)) %>%
  distinct(region, site, year, burrow_name) %>%
  merge(burrow_0, by = c('region', 'year', 'site')) 

#df containing all data for only days observed
burrow_1 <- burrow %>%
  select(region, site, year, date, yday, study_day, start_day, end_day, burrow_name, burrow_visit, tot_prey) %>%
  select(-c(start_day, end_day, date, yday)) %>%
  merge(burrow_name_expand, by = c('region', 'year', 'site', 'burrow_name', 'study_day'), all = T) %>%
  filter(!is.na(burrow_name)) %>%
  transform(burrow_visit = ifelse(is.na(burrow_visit), 0, burrow_visit)) %>%
  transform(tot_prey = ifelse(is.na(tot_prey), 0, tot_prey))

#df containing all study days per year, region, site, burrow name - no data
burrow_2 <- burrow_1 %>%
  distinct(region, year, site, burrow_name) %>%
  merge(all_days, all = T)  #%>% arrange(burrow_name)

#combining all data with dummy framework of all days
burrow_CH <- burrow_2 %>%
  merge(burrow_1, by = c('region', 'site', 'year', 'burrow_name', 'study_day'), all.x = T) %>%
  merge(start_end_visits, by = c('region', 'year', 'site', 'burrow_name'), all.x = T) %>%
  transform(prey_days = prey_end + 1 - prey_start) %>%
  transform(bv_days = bv_end + 1 - bv_start) %>%
  transform(capt_hist = ifelse(study_day == 0, 3, #not observed (dummy day)
              ifelse(is.na(burrow_visit) & is.na(tot_prey), NA, #not observed
                     ifelse(burrow_visit == 0 & tot_prey == 0, 3, #observed but not detected
              ifelse(tot_prey > 0, 2, #prey visit
              ifelse(burrow_visit > 0, 1, #burrow visit
                       100)))))) %>%
  select(region, year, site, study_day, burrow_name, capt_hist) %>%
  distinct()

test <- burrow_CH %>% 
  #filter(capt_hist == 100)
  #filter(capt_hist != 'NA')
  filter(is.na(capt_hist))
hist(burrow_CH$capt_hist)
table(burrow_CH$capt_hist)

dup_test <- burrow_CH[duplicated(burrow_CH),]

burrow_CHcovs <- burrow_CH %>%
  merge(tides_dat %>% 
          dplyr::select(region, site, v, from_hilo, year, burrow_name, study_day), 
        by = c('region', 'site', 'year', 'burrow_name', 'study_day'), all.x = T, all.y = F)
 
# #will be rows that are in tides_dat but not burrow
# test <- anti_join(burrow_CHcovs, burrow_CH) %>%
#      filter(site == 'Bush Point Dock' & year == 2016)
# 
# 
# test2 <- burrow_CH %>%
#   filter(site == 'Bush Point Dock' & year == 2016)
# 
# test3 <- data_burrow_all %>%
#   filter(site == 'Bush Point Dock' & year == 2016)

#write.csv(burrow_CH, "burrow_CH.csv", row.names = F) #dim(before tides) = 225759,6
  
```



Questions
- What to do when see one prey delivery and no other visits?
  
- Excluded single burrow visits, but included single date burrow visits where bv > 1

- Haven't trimmed total "study length" to nest level (currently year level)

- If last burrow visit was last prey delivery, could have just missed the rest of the visits?
