
## This file creates the data for the mark-resight multi-event model with both sexes, run in SSL_IPM.Rmd, and includes data visualization/exploration for number of resights, resight locations, etc.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(rstudioapi)
library(rjags)
library(jagsUI)
library(R2OpenBUGS)
library(dplyr)
library(tidyr)
library(reshape2)
library(data.table)
library(ggplot2)
library(scales)
library(knitr)
library(stringr)
library(lubridate)
library(stats) 
library(zoo)
#library(nimble)

path <- getActiveDocumentContext()$path 
setwd(dirname(path))

# source('PlotTheme.R')

```

```{r data}

#reference of all sites by region, complex, RCA, and whether rookery or haul-out
super_ref <- read.csv('Data/superRef_SSL.csv') %>%
  dplyr::rename(SiteName = Site) %>%
  dplyr::select(c(Complex, SiteName, RCA, LAT, LON, Region, Rookery))

#initial branding data (weight, length, date, region, lat/long)
inits <- read.csv("Data/initial_capture_data.csv", header = T, stringsAsFactors = F) %>%
  merge(super_ref, by = 'SiteName', all.y = F)

#females only, ID, capture year/region/sight, sex, weight, length
init_ref <- inits %>%
  dplyr::select(AnimalID, Year, Region, SiteName, Sex, Mass_kg, StandardLength_cm, AdjustedSex) %>%
  transform(Sex = ifelse(!is.na(AdjustedSex), AdjustedSex, Sex)) %>%
  dplyr::rename(t_0 = Year, site_0 = SiteName, reg_0 = Region) %>%
  filter(Sex == 'F')

#merge with refs for weight, natal region/year
resights <- read.csv("Data/resight_data.csv", header = T, stringsAsFactors = F) %>%
  transform(date = mdy(date)) %>%
  transform(year = year(date)) %>% #60K
  merge(init_ref, by = c('AnimalID'), all.y = T) %>% #females only; 37K
  merge(super_ref %>%
          dplyr::select(Complex, SiteName, Region, Rookery) %>%
          dplyr::rename(Region_ref = Region), by = 'SiteName', all.x = T) %>%
  transform(years_old = year - t_0) %>%
  transform(SiteName = toupper(SiteName)) %>%
  transform(SiteName = trimws(SiteName, which = c("both", "left", "right"))) %>%
  dplyr::select(-c(Age, Time, Sex.x, Beach, datetime, Behavior)) %>% dplyr::rename(Sex = Sex.y) %>%
  transform(age_cat = ifelse(years_old == 0, 'P',
                             ifelse(years_old == 1, '1',
                                    ifelse(years_old == 2, '2',
                                           ifelse(years_old == 3, '3',
                                                  ifelse(years_old == 4, '4',
                                                         ifelse(years_old == 5, '5',
                                                                ifelse(years_old > 5, '6+', '100'))))))))

#create simple region reference df (site & region)
region_ref <- resights %>%
  filter(!is.na(Region)) %>%
  distinct(SiteName, Region) %>%
  dplyr::rename(reg_ref = Region)

#number of resights per animal per year
resight_num <- resights %>%
  group_by(AnimalID, year) %>%
  dplyr::summarize(resights = n_distinct(date))

#fix NA region and add number of resights
resights <- resights %>%
  merge(region_ref, by = 'SiteName', all = T) %>%
  transform(Region = ifelse(is.na(Region), reg_ref, Region)) %>%
  merge(resight_num, by = c('AnimalID', 'year')) 

#Number of unique pup_ev per year per animalID; 
#most unambiguous (only 1222 of 8445 more than 1 evidence category)
#pup evidence is a value 1-3, an average of expert's votes for whether there was ev of pup
#table(resights$pup_evidence) 

#find maximum 'pup evidence' value per year per animal 
max_pup <- resights %>%
  group_by(AnimalID, year) %>%
  dplyr::summarize(pup_status_yr = max(pup_evidence)) %>%
  transform(pup_cat = ifelse(pup_status_yr == 3, 1, 0)) #assign reprod status (1 or 0) using only 3s (pup for sure)

#and then remerge max_pup onto resights, standardize weight, length, create bmi
data_f <- resights %>%
  merge(max_pup, by = c('AnimalID', 'year')) %>%
  transform(pup_evidence = round(pup_evidence, 1)) %>%
  distinct(AnimalID, year, Region, reg_0, site_0, t_0, Sex, resights,
           Mass_kg, StandardLength_cm, years_old, age_cat, pup_status_yr, pup_cat) %>%
  #fixing a few P, 1, and 2s with pups -- errors
  transform(pup_cat = ifelse(years_old < 4 & pup_cat == 1, 0, pup_cat)) %>% 
  transform(pup_fact = ifelse(pup_cat == 1, 'P', 'U')) %>%
  transform(obs = paste0(age_cat, pup_fact)) %>%  #create categories of with pup and unk per age
  transform(bmi = Mass_kg/((StandardLength_cm/100)*(StandardLength_cm/100))) %>%
  transform(bmi_std = scale(bmi)) %>%
  transform(len_std = scale(StandardLength_cm)) %>%
  transform(weight_std = scale(Mass_kg))  %>%
  dplyr::select(AnimalID, year, Sex, resights, reg_0, t_0, obs, weight_std, len_std, bmi_std) %>%
  arrange(t_0, AnimalID) %>%
  #filter(reg_0 != grepl('BERING', reg_0)) %>%
  distinct() %>% #check why there are duplicates! I think this would be same animal seen in dif regions/yr?
  transform(ch = as.numeric(factor(obs, levels = c('PU', '1U', '2U', '3U',
                                                   '4U', '4P', '5U', '5P', '6+U', '6+P', 'ND')))) %>%
  dplyr::select(-obs) %>%
  filter(t_0 < 2017) %>%
  dcast(AnimalID + reg_0 + t_0 + weight_std + len_std + bmi_std + Sex ~ year, value.var = 'ch', fill = 11)

#males
init_ref_m <- inits %>%
  dplyr::select(AnimalID, Year, Region, SiteName, Sex, Mass_kg, StandardLength_cm, AdjustedSex) %>%
  transform(Sex = ifelse(!is.na(AdjustedSex), AdjustedSex, Sex)) %>%
  dplyr::rename(t_0 = Year, site_0 = SiteName, reg_0 = Region) %>%
  filter(Sex == 'M')

#merge with refs for weight, natal region/year
resights_m <- read.csv("Data/resight_data.csv", header = T, stringsAsFactors = F) %>%
  transform(date = mdy(date)) %>%
  transform(year = year(date)) %>% #60K
  merge(init_ref_m, by = c('AnimalID'), all.y = T) %>% #females only; 37K
  merge(super_ref %>%
          dplyr::select(Complex, SiteName, Region, Rookery) %>%
          dplyr::rename(Region_ref = Region), by = 'SiteName', all.x = T) %>%
  transform(years_old = year - t_0) %>%
  transform(SiteName = toupper(SiteName)) %>%
  transform(SiteName = trimws(SiteName, which = c("both", "left", "right"))) %>%
  dplyr::select(-c(Age, Time, Sex.x, Beach, datetime, Behavior)) %>% dplyr::rename(Sex = Sex.y) %>%
  transform(age_cat = ifelse(years_old == 0, 'P',
                             ifelse(years_old == 1, '1',
                                    ifelse(years_old == 2, '2',
                                           ifelse(years_old == 3, '3',
                                                  ifelse(years_old == 4, '4',
                                                         ifelse(years_old > 4, '5+', '100'))))))) %>%
  transform(age_cat = factor(paste0(age_cat, 'M')))

#create simple region reference df (site & region)
region_ref_m <- resights_m %>%
  filter(!is.na(Region)) %>%
  distinct(SiteName, Region) %>%
  dplyr::rename(reg_ref = Region)

#number of resights per animal per year
resight_num_m <- resights_m %>%
  group_by(AnimalID, year) %>%
  dplyr::summarize(resights = n_distinct(date))

#fix NA region and add number of resights
resights_m <- resights_m %>%
  merge(region_ref_m, by = 'SiteName', all = T) %>%
  transform(Region = ifelse(is.na(Region), reg_ref, Region)) %>%
  merge(resight_num_m, by = c('AnimalID', 'year')) 

data_m <- resights_m %>%
  distinct(AnimalID, year, Region, reg_0, site_0, t_0, Sex, resights,
           Mass_kg, StandardLength_cm, years_old, age_cat) %>%
  transform(pup_status_yr = 0, pup_cat = 0, pup_fact = factor(as.character('M'))) %>% 
  transform(obs = age_cat) %>%  
  transform(bmi = Mass_kg/((StandardLength_cm/100)*(StandardLength_cm/100))) %>%
  transform(bmi_std = scale(bmi)) %>%
  transform(len_std = scale(StandardLength_cm)) %>%
  transform(weight_std = scale(Mass_kg)) %>%
  dplyr::select(AnimalID, year, Sex, resights, reg_0, t_0, obs, weight_std, len_std, bmi_std) %>%
  arrange(t_0, AnimalID) %>%
  #filter(reg_0 != grepl('BERING', reg_0)) %>%
  distinct() %>% #check why there are duplicates! I think this would be same animal seen in dif regions/yr?
  transform(ch = as.numeric(factor(obs, levels = c('PM', '1M', '2M', '3M', '4M', '5+M')))) %>%
  dplyr::select(-obs) %>%
  filter(t_0 < 2017) %>%
  dcast(AnimalID + reg_0 + t_0 + weight_std + len_std + bmi_std + Sex ~ year, value.var = 'ch', fill = 7)

data <- bind_rows(data_f, data_m) %>%
    arrange(t_0, AnimalID)

data[which(is.na(data$len_std)), 'len_std'] <- 0 #just three cases
data[which(is.na(data$bmi_std)), 'bmi_std'] <- 0

# ch_all <- data

ch_fem <- data %>% filter(Sex == 'F') %>% arrange(t_0, AnimalID)
ch_m <- data %>% filter(Sex == 'M') %>% arrange(t_0, AnimalID)

#create num_resight
#convert char ch to factor/numerical
  
ch_df <- resights %>%
  distinct(AnimalID, year, Region, reg_0, site_0, t_0, Sex, resights,
           Mass_kg, StandardLength_cm, years_old, age_cat) %>%
  transform(pup_status_yr = 0, pup_cat = 0, pup_fact = factor(as.character('M'))) %>% 
  transform(obs = age_cat) %>%  
  transform(bmi = Mass_kg/((StandardLength_cm/100)*(StandardLength_cm/100))) %>%
  transform(bmi_std = scale(bmi)) %>%
  transform(len_std = scale(StandardLength_cm)) %>%
  transform(weight_std = scale(Mass_kg)) %>%
  dplyr::select(AnimalID, year, Sex, resights, reg_0, t_0) %>%
  #filter(reg_0 != grepl('BERING', reg_0)) %>%
  distinct() %>% #check why there are duplicates! I think this would be same animal seen in dif regions/yr?
  filter(t_0 < 2017) %>%
  arrange(AnimalID, t_0)

#number of times individual seen per year for use as covariate on delta (prob of pup assignment)
#don't need this 'all' since don't need male resights, just num_resight that already exists
num_resight_all <- ch_df %>% arrange(t_0, AnimalID) %>%
  dcast(AnimalID + t_0 + Sex ~ year, value.var = 'resights', fill = 0) %>%
  melt(id.vars = c('AnimalID', 't_0', 'Sex')) %>%
  transform(resights = ifelse(value < 1, 4, #4 for not detected
                      ifelse(value > 8, 3,  #greater than 8 is high/3
                         ifelse(value < 9 & value > 2, 2, #resighted 3-8 is med/2
                              ifelse(value < 3, 1, 100))))) %>% #1-2 times is low
  dcast(AnimalID + t_0 + Sex ~ variable, value.var = 'resights')

setwd("~/Documents/SAFS/Stellers/SSL_IPM")
# ******main dfs - careful when re-writing******
# write.csv(num_resight_all, 'num_resight_all.csv', row.names = F)
# write.csv(ch_all, 'ch_all.csv', row.names = F)
write.csv(ch_fem, 'ch_fem.csv', row.names = F)
write.csv(ch_m, 'ch_m.csv', row.names = F)

```

Data exploration and visualization
```{r resight locs}
#CODE NOT UPDATED FOR ADDITION OF MALES - leaving in case I want to look, but will need work

#resight N and locations, can use resights or robust_data
#looked at this because Sarah and I were wondering how often females (particularly with pups) were seen in multiple locations in service of figuring out how to deal with prob of pup ascertainment with different number of times and locations seen.

resights <- resights_m %>%
  bind_rows(resights)

ggplot(resight_num, aes(resight_num$resights)) +
  geom_histogram(binwidth = 1) 
table(resight_num$resights)

#number of regions each individual was cited each year
loc_num <- resights %>%
  group_by(AnimalID, year, reg_0, age_cat) %>%
  filter(!is.na(Region)) %>%
  summarize(cnt = n_distinct(Region)) %>%
  filter(cnt > 1)

#number cited in different locations in a given year
loc_summary <- loc_num %>%
  group_by(year, age_cat) %>%
  summarize(cnt = n_distinct(AnimalID))

#~54 animals seen in different regions, 316 at different sites
n_distinct(loc_num$AnimalID)


ggplot(loc_summary, aes(x = year, y = cnt, group = age_cat, fill = age_cat)) +
  geom_bar(stat = 'identity') +
  #geom_line() +
  ylab('Number of Individuals in 1+ Region') + xlab('') +
  plot_theme() +
  scale_fill_brewer(palette = 'Spectral') +
  scale_color_brewer(palette = 'Spectral')

```

```{r site resight freq}

#resights by location and year
robust_data <- resights %>%
  merge(max_pup, by = c('AnimalID', 'year')) %>%
  transform(pup_evidence = round(pup_evidence, 1)) %>%
  transform(pup_cat = ifelse(years_old < 4 & pup_cat == 1, 0, pup_cat)) %>%
  transform(pup_fact = ifelse(pup_cat == 1, 'P', 'U')) %>%
  #transform(obs = ifelse(age_cat == 'P', 'P', paste0(age_cat, pup_fact)))
  #transform(bmi = Mass_kg/((StandardLength_cm/100)*(StandardLength_cm/100))) %>%
  transform(obs = paste0(age_cat, pup_fact)) #%>%
  # merge(mean_weight) %>%
  # transform(weight_std = (Mass_kg - mean_wt)/sd) %>%
  # merge(mean_len) %>%
  # transform(len_std = (StandardLength_cm - mean_len)/sd_len) %>%
  # dplyr::select(-c(mean_wt, sd, mean_len, sd_len))

#number branded at each field camp per year
loc_yr <- inits %>%
  group_by(Year, Region, SiteName) %>% 
  summarize(cnt = n_distinct(AnimalID)) %>%
  transform(SiteName = factor(SiteName, levels = c('MARMOT', 'SUGARLOAF',
                                                   'UGAMAK/NORTH', 'UGAMAK/UGAMAK BAY',
                                                   'SEAL ROCKS', 'WOODED (FISH)', 'CHISWELL ISLANDS'),
                              labels = c('Marmot', 'Sugarloaf', 'Ugamak North', 'Ugamak Bay',
                                         'Seal Rocks', 'Wooded', 'Chiswell Isl')))

ggplot(loc_yr, aes(factor(as.numeric(Year)), cnt, col = SiteName, group = SiteName, fill = SiteName)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~Region) + ylab('Branded Pups') + xlab('') +
  plot_theme(legend.position = 'bottom',
             legend.title = element_blank()) +
  scale_x_discrete(breaks = c(2000:2017), labels = c(2000:2017)) +
  scale_fill_manual(values = rainbow) +
  scale_color_manual(values = rainbow) 

#frequency of resights by site type - most resights at rookeries
ggplot(resights, aes(year, col = factor(Rookery), fill = factor(Rookery))) +
  geom_bar() + 
  xlab('') + ylab('Resighted Individuals') +
  theme(panel.grid = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA),
        legend.title = element_blank(),
        axis.text = element_text(size = 11),
        axis.title = element_text(size = 12),
        legend.text = element_text(size = 10),
        legend.position = 'top',
        legend.key.size = unit(1, 'lines')) +
  scale_fill_manual(values = rainbow) + scale_color_manual(values = rainbow) +
  guides(fill = guide_legend(nrow = 1))

ggplot(robust_data %>% filter(Rookery == 0), 
       aes(x = factor(year), col = factor(obs), fill = factor(obs))) +
  geom_bar(stat = 'count', position = 'stack') + 
  xlab('') + ylab('Resighted Individuals') +
  theme(panel.grid = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA),
        legend.title = element_blank(),
        axis.text = element_text(size = 11, angle = 90),
        axis.title = element_text(size = 12),
        legend.text = element_text(size = 10),
        legend.position = 'top',
        legend.key.size = unit(1, 'lines')) +
  #scale_fill_manual(values = rainbow) + scale_color_manual(values = rainbow) +
  scale_fill_brewer(palette = "Paired") +
    scale_color_brewer(palette = "Paired") +
  guides(fill = guide_legend(nrow = 1))

#Field camps are Marmot, Ugamak/ugamak bay
sights <- robust_data %>% 
  dplyr::select(AnimalID, obs, age_cat, years_old, year, SiteName, Region, Rookery) %>%
  transform(sitetype = ifelse(SiteName %in% c('MARMOT', 'UGAMAK/UGAMAK BAY'), 'FC', 
                              ifelse(Rookery == 1, 'R', 'H'))) %>%
  transform(sitetype = factor(sitetype, levels = c('FC', 'R', 'H'),
                              labels = c('FC', 'R', 'H')))

#frequency of resights for each possible obs per year
freq <- sights %>% filter(!is.na(sitetype)) %>%
  dcast(sitetype + year ~ obs) 

obs_group <- c('1U', '2U', '3U', '4U', '5P', '5U', '6+P', '6+U', 'PU')

#number of observations per animalID per year for 3+ yo
freq_B <- sights %>% filter(!is.na(sitetype)) %>%
  filter(years_old > 3 & sitetype != 'H') %>%
  transform(obs_loc = paste(obs, sitetype, sep = '_')) %>%
  dplyr::select(AnimalID, year, years_old, obs_loc) %>%
  dcast(AnimalID + year + years_old ~ obs_loc) 
freq_B <- freq_B %>%
  mutate(sum = rowSums(freq_B[,4:15])) %>%
  filter(sum > 0) 

freq_B_perc <- data.frame(freq_B[,1:3], round(freq_B[,4:15]/freq_B[,'sum'], 2)) 
colnames(freq_B_perc) <- gsub("X", '', colnames(freq_B_perc))

### combined years, this problematic moving around happens 36 times with pup, not even U obs
#6+year olds seen with pups in a given year at both rookery and FC 24 times
checks <- freq_B_perc %>%
  melt(id.vars = c('AnimalID', 'year', 'years_old')) %>%
  filter(variable == '6.P_FC' & value != 0 & value !=1| variable == '6.P_R'& value != 0 & value !=1) %>%
  arrange(AnimalID, year)
#5year olds seen with pups in a given year at both rookery and FC 8 times
checks <- freq_B_perc %>%
  melt(id.vars = c('AnimalID', 'year', 'years_old')) %>%
  filter(variable == '5P_FC' & value != 0 & value !=1| variable == '5P_R'& value != 0 & value !=1) %>%
  arrange(AnimalID, year)
#4year olds seen with pups in a given year at both rookery and FC 4 times
checks <- freq_B_perc %>%
  melt(id.vars = c('AnimalID', 'year', 'years_old')) %>%
  filter(variable == '4P_FC' & value != 0 & value !=1| variable == '4P_R'& value != 0 & value !=1) %>%
  arrange(AnimalID, year)

# freq_mean <- freq_B_perc %>%
#   group_by(year) %>%
#   summarize()

# > unique(resights$site_0)
# [1] "MARMOT"            "SUGARLOAF"         "UGAMAK/NORTH"      "UGAMAK/UGAMAK BAY" "SEAL ROCKS"       
# [6] "CHISWELL ISLANDS"  "WOODED (FISH)"

#the question is what is the frequency/proportion of sightings for breeders by breeding status and site type


```


```{r annual resights}

plot_data <- resights %>%
  transform(Region = factor(Region, levels = c('BERING', 'E ALEU', 'W GULF', 'C GULF', 'E GULF', 'SE AK')))

#resights per year per natal region
ggplot(plot_data %>% filter(!is.na(reg_0)), aes(year, col = reg_0, fill = reg_0)) +
  geom_bar() + xlab('') + ylab('Resighted Individuals') +
  theme(panel.grid = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA),
        legend.title = element_blank(),
        axis.text = element_text(size = 11),
        axis.title = element_text(size = 12),
        legend.text = element_text(size = 10),
        legend.position = 'top',
        legend.key.size = unit(1, 'lines')) +
  scale_fill_manual(values = rainbow) + scale_color_manual(values = rainbow) +
  guides(fill = guide_legend(nrow = 1))
#per natal site
ggplot(plot_data %>% filter(!is.na(site_0)), aes(year, col = site_0, fill = site_0)) +
  geom_bar() + xlab('') + ylab('Resighted Individuals') +
  theme(panel.grid = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA),
        legend.title = element_blank(),
        axis.text = element_text(size = 11),
        axis.title = element_text(size = 12),
        legend.text = element_text(size = 8),
        legend.position = 'top',
        legend.key.size = unit(1, 'lines')) +
  scale_fill_manual(values = rainbow) + scale_color_manual(values = rainbow) +
  guides(fill = guide_legend(nrow = 1))
#per region
ggplot(plot_data %>% filter(!is.na(Region)), aes(year, col = Region, fill = Region)) +
  geom_bar() + xlab('') + ylab('Resighted Individuals') +
  theme(panel.grid = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA),
        legend.title = element_blank(),
        axis.text = element_text(size = 11),
        axis.title = element_text(size = 12),
        legend.text = element_text(size = 8),
        legend.position = 'top',
        legend.key.size = unit(1, 'lines')) +
  facet_wrap(~Sex) +
  scale_fill_manual(values = rainbow) + scale_color_manual(values = rainbow) +
  guides(fill = guide_legend(nrow = 1))
#per age cat
ggplot(plot_data %>% filter(!is.na(Region)), aes(year, col = age_cat, fill = age_cat)) +
  geom_bar() + xlab('') + ylab('Resighted Individuals') +
  theme(panel.grid = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA),
        legend.title = element_blank(),
        axis.text = element_text(size = 11),
        axis.title = element_text(size = 12),
        legend.text = element_text(size = 8),
        legend.position = 'top',
        legend.key.size = unit(1, 'lines')) +
  scale_fill_manual(values = rainbow) + scale_color_manual(values = rainbow) +
  guides(fill = guide_legend(nrow = 1))

```


