---
title: ""
output: word_document
---

```{r setup, include=FALSE}
library(tidyr)
library(data.table)
library(ggfortify)
library(broom) #tidy() augment()
library(dplyr)
library(ggplot2)
library(cowplot)
library(lme4)
library(lmerTest)
library(scales)
library(reshape2)
library(stats) 
library(zoo)
library(sciplot)
library(jagsUI)
library(chron)
 
setwd("~/Documents/R/SAFS/PigeonGuillemots")
path <- getActiveDocumentContext()$path 
setwd(dirname(path))

# knitr::opts_chunk$set(echo = TRUE)
```


```{r set up long df}

#load data from PigeonGuillemot_whidbey.Rmd
#contains single row where burrow_name == NA when no activity was detected, but survey started
data_burrow_all <- read.csv("data_burrow.csv", header = T, stringsAsFactors = F) %>%
  filter(region == 'Whidbey') %>%
  #dplyr::select(-intern_data) %>%
  dplyr::select(-c(Gunnel, Sculpin, Other)) %>%
  #filter(site == 'Mutiny Sands') %>%
  distinct()  #2 duplicates, all lagoon south 2017

# test <- data_burrow_all %>%
#   distinct(region, site, year, week, yday, burrow_name, tot_prey) %>%
#   group_by(site, year, week, burrow_name) %>%
#   summarize(cnt = n_distinct(yday)) %>%
#   filter(cnt > 1)
# tail(test)

# data_count <- read.csv("data_count.csv", header = T, stringsAsFactors = F) %>%
#   select(-intern_data)

#study start day per year, island-wide
start_end_all <- data_burrow_all %>%
  group_by(year, region) %>%
  summarize(start_day = min(yday), end_day = max(yday))

no_vis <- data_burrow_all %>%
  filter(is.na(burrow_name)) %>%
  dplyr::select(region, year, site, week, yday)
name_expand <- data_burrow_all %>%
  filter(!is.na(burrow_name)) %>% #use all unique burrow names per year to expand each per week
  distinct(region, year, site, burrow_name) %>%
  merge(no_vis, all = T) %>%
  filter(!is.na(week)) #remove cases where there aren't any missings

burrow <- data_burrow_all %>%
  filter(!is.na(burrow_name)) %>% #remove all dummy rows where no burrows were seen
  bind_rows(name_expand) %>%
  #distinct() %>%
  merge(start_end_all, by = c('region', 'year'), all = T) %>%
  transform(study_day = yday - start_day + 1) 

#burrow visit and prey visit start stops
prey_start_end <- burrow %>%
  filter(tot_prey > 0) %>%
  group_by(region, year, site, burrow_name) %>%
  summarize(prey_start = min(study_day), prey_end = max(study_day))  

bv_start_end <- burrow %>%
  filter(burrow_visit > 0) %>%
  group_by(region, year, site, burrow_name) %>%
  summarize(bv_start = min(study_day), bv_end = max(study_day))  

start_end_visits <- prey_start_end %>%
  merge(bv_start_end, by = c('region', 'year', 'site', 'burrow_name'), all = T)

week_range <- burrow %>%
  group_by(region, year, site) %>%
  summarize(min_week = min(week), max_week = max(week))

#looking at where these long week ranges are coming from:
#ledgewood 2016 is the long one, otherwise mostly 8-11 weeks
test <- week_range %>%
  transform(range = max_week-min_week) #%>%
  filter(range > 11)
hist(test$range)
table(test$range)

#combining all data with dummy framework of all days
burrow_CH <- burrow %>%
  merge(start_end_visits, by = c('region', 'year', 'site', 'burrow_name'), all.x = T) %>%
  transform(prey_days = prey_end + 1 - prey_start) %>%
  transform(bv_days = bv_end + 1 - bv_start) %>%
  group_by(region, year, site) %>%
  merge(week_range, by = c('region', 'year', 'site')) %>%
  #transform(effort = ifelse(is.na(burrow_visit) & is.na(tot_prey), 0, 1)) %>%
  transform(capt_hist = ifelse(is.na(burrow_visit) & is.na(tot_prey), 3, #observed but not detected
                     ifelse(burrow_visit == 0 & tot_prey == 0, 3, #observed but not detected
              ifelse(tot_prey > 0, 2, #prey visit
              ifelse(burrow_visit > 0, 1, #burrow visit
                       100))))) %>% 
  select(region, year, site, week, yday, start_day, study_day, min_week, max_week, burrow_name, capt_hist) %>%
  distinct() %>%
  distinct(region, year, site, burrow_name, min_week, max_week, yday, study_day, week, capt_hist) %>% 
  distinct() %>%
  dcast(region + year + site + burrow_name + min_week + max_week ~ week, value.var = 'capt_hist', 
        fill = 3, fun.aggregate = mean) %>%
  filter(!is.na(burrow_name))

#now we have ch df, but too many 3s - need to make NA outside site-specific start/stop weeks
burrow_CH <- burrow_CH %>%
  melt(id.vars = c('region', 'year', 'site', 'burrow_name', 'min_week', 'max_week')) %>%
  transform(week = as.numeric(as.character(variable))) %>%
  transform(capt_hist = ifelse(week < min_week | week > max_week, 'NA', value)) %>%
  dplyr::select(region, year, site, burrow_name, week, capt_hist) %>%
  dcast(region + year + site + burrow_name ~ week, value.var = 'capt_hist')

```

```{r}

#days-between
eff_day <- burrow %>%
  merge(start_end_visits, by = c('region', 'year', 'site', 'burrow_name'), all.x = T) %>%
  transform(prey_days = prey_end + 1 - prey_start) %>%
  transform(bv_days = bv_end + 1 - bv_start) %>%
  group_by(region, year, site) %>%
  merge(week_range, by = c('region', 'year', 'site')) %>%
  distinct(region, year, site, burrow_name, start_day, yday, week, min_week, max_week) %>% 
  #distinct() %>%
  dcast(region + year + site + start_day + burrow_name + min_week + max_week ~ week, value.var = 'yday',
        fun.aggregate = mean) %>%
  filter(!is.na(burrow_name)) %>%
  melt(id.vars = c('region', 'year', 'site', 'burrow_name', 'start_day', 'min_week', 'max_week')) %>%
  transform(week = as.numeric(as.character(variable))) %>%
  transform(value = ifelse(week < min_week | week > max_week, 'NA', value)) %>%
  dplyr::select(region, year, site, start_day, burrow_name, week, value) %>%
  dcast(region + year + site + burrow_name + start_day ~ week, value.var = 'value')

#NaN is unseen, NA is no survey
days_bet <- eff_day[,6:(dim(eff_day)[2])]

# get.first <- function(x) min(which(x != 'NA'))
# f <- apply(days_bet, 1, get.first)

# get.last <- function(x) max(which(x < 3))
# l <- apply(days_bet, 1, get.last)

days <- matrix(NA, nrow = dim(days_bet)[1], ncol = dim(days_bet)[2])
for (i in 1:dim(days_bet)[2]) {
  days[,i] <- as.numeric(days_bet[,i])-147 #make it into study day rather than year day
}
days <- data.frame(days)

#####from mark
time.Since.Last <- This.minus.last<-matrix(NA,nrow=nrow(days),ncol=ncol(days))

for (i in 1:nrow(days)){
  rowSub <- days[i,] 
  for(j in 2:ncol(days)){
    if(!is.na(rowSub[j])){  #if col position isn't na, then 
    subRowCol <- rowSub[1:(j-1)]
    if(sum(!is.na(subRowCol)) > 0){ #if it isn't all NAs
      lastCol <- max(which(!is.na(subRowCol)))
      time.Since.Last[i,j] <- j-lastCol
      This.minus.last[i,j] <- rowSub[,j]-rowSub[,lastCol]
      days_since <- data.frame(round(This.minus.last))
      }
    }
  }
}

#days_since

#df of 1 when nest was detected, 0 when not
# nest_det <- burrow %>%
#   merge(start_end_visits, by = c('region', 'year', 'site', 'burrow_name'), all.x = T) %>%
#   transform(prey_days = prey_end + 1 - prey_start) %>%
#   transform(bv_days = bv_end + 1 - bv_start) %>%
#   transform(effort = ifelse(is.na(burrow_visit) & is.na(tot_prey), 0, 1)) %>%
#   dcast(region + year + site + burrow_name ~ week, value.var = 'effort', fill = 0)
```


```{r covariates}

#sst
sst <- read.csv('sst_day.csv', header = T, stringsAsFactors = F) %>%
  #transform(year = factor(year)) %>%
  filter(station == 9444900) %>% #CHECK if this is the north seattle station!
  dplyr::select(-c(station, month, day)) %>%
  merge(burrow %>% dplyr::select(yday, year, study_day) %>% distinct(), by = c('year', 'yday')) 

#tides
tides <- read.csv("tides_all.csv", stringsAsFactors = F, header = T) %>%
  transform(date = as.Date(date)) %>%
  transform(month = month(date)) %>%
  transform(time = as.POSIXct(time)) 
    
#high and low tides, dim from data_count doubles
## problematic to use the count data since some dates are missing compared to burrow (maylor 2008)
PG_covs <- burrow %>% 
  filter(region == 'Whidbey') %>%
  #filter(PG_count != '') %>% 
  select(region, year, site, date, start_time, week, yday, burrow_name, burrow_visit, tot_prey,
         start_day, end_day, study_day) %>%
  transform(date = as.Date(date)) %>%
  merge(tides %>% filter(region == 'Whidbey'), by = c('site', 'date', 'region'), all.x = T) %>%
  transform(start_time = ifelse(start_time == "0:00" | start_time == "", "8:00", start_time)) %>%
  transform(survey = as.POSIXlt(paste0(paste(date, start_time, sep = " "), ":00"))) %>%
  transform(from_low = ifelse(type == "L", as.numeric(time-survey, units = "mins"), NA),
            from_high = ifelse(type == "H", as.numeric(time-survey, units = "mins"), NA)) %>%
  transform(from_hilo = as.numeric(coalesce(from_low, from_high))) %>%
  select(-c(t, month, from_low, from_high)) %>%
  transform(time_stamp = times(format(time, format = "%H:%M:%S"))) %>%
  transform(rank = ifelse(time_stamp <= "2:30:00" | time_stamp >= "21:00:00", 1,
                          ifelse(time_stamp > "3:00:00" & time_stamp <= "9:00:00", 2,
                                 ifelse(time_stamp > "17:00:00", 4, 3)))) %>%
  filter(rank == 2 | rank == 3) %>%
  filter(type == 'H') %>%
  dplyr::select(region, year, site, date, v, from_hilo,
                burrow_name, burrow_visit, tot_prey, start_day, end_day, study_day) %>%
  merge(sst, by = c('study_day', 'year'), all.x = T) %>%
  dplyr::select(region, year, site, study_day, burrow_name, from_hilo, v, temp)

```


```{r ch} 

# all_dat <- burrow_CH %>%
#   merge(PG_covs, by = c('region', 'year', 'site', 'study_day', 'burrow_name'), all = T)

write.csv(days_since, "days_since.csv", row.names = F) 
write.csv(burrow_CH, "burrow_CH.csv", row.names = F) 
# write.csv(all_dat, 'all_dat.csv', row.names = F)
  
```



Questions
- What to do when see one prey delivery and no other visits?
  
- Excluded single burrow visits, but included single date burrow visits where bv > 1

- Haven't trimmed total "study length" to nest level (currently year level)

- If last burrow visit was last prey delivery, could have just missed the rest of the visits?
